### ISSUE TITLE
install

### ISSUE THREAD

**Issue by travlytle** [mdonoughe/modem_status#2]
Could you provide instructions (or point me to an example) on how to install this into Home Assistant? I'm new to HA and not sure how it's done.

**Comment by mdonoughe** [comment]
This isn't a Home Assistant component and needs to be run separately. I guess it could be an addon, but I have only ever used the core version and it doesn't have addons. It could probably be rewritten as a custom component.

I think it needs more work before it could be a quality component. The modem firmware sometimes changes unexpectedly, causing this to stop working, and there's a bug in the modem firmware where the web interface sometimes just stops responding until you reboot the modem.

**Comment by travlytle** [comment]
Understood, thanks for the work.
